{{- $authIdMount := "/authId" }}
{{- $authPasswordMount := "/authIdPassword" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cert-manager-webhook-cloudns.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cert-manager-webhook-cloudns.name" . }}
    spec:
      serviceAccountName: {{ include "cert-manager-webhook-cloudns.fullname" . }}
      containers:
        - name: {{ .Chart.Name | quote }}
          {{- $repo := print .Values.image.registry "/" .Values.image.repository }}
          {{- if .Values.image.digest }}
          image: {{ print $repo "@" .Values.image.digest | quote }}
          {{- else }}
          image: {{ print $repo ":" (.Values.image.tag | default .Chart.AppVersion) | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/certs/tls.crt
            - --tls-private-key-file=/certs/tls.key
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
            - name: CLOUDNS_AUTH_ID_FILE
              {{- if kindIs "map" .Values.clouDNS.authId }}
              value: {{ print $authIdMount "/" .Values.clouDNS.authId.key |  quote }}
              {{- else }}
              value: {{ print $authIdMount "/authId" |  quote }}
              {{- end }}
            - name: CLOUDNS_AUTH_PASSWORD_FILE
              {{- if kindIs "map" .Values.clouDNS.authPassword }}
              value: {{ print $authPasswordMount "/" .Values.clouDNS.authPassword.key |  quote }}
              {{- else }}
              value: {{ print $authPasswordMount "/authPassword" |  quote }}
              {{- end }}
            - name: CLOUDNS_AUTH_ID_TYPE
              value: {{ .Values.clouDNS.authIdType }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: auth-id
              mountPath: {{ $authIdMount | quote }}
              readOnly: true
            - name: auth-password
              mountPath: {{ $authPasswordMount | quote }}
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "cert-manager-webhook-cloudns.servingCertificate" . }}
        - name: auth-id
          secret:
            {{- if kindIs "map" .Values.clouDNS.authId }}
            secretName: {{ .Values.clouDNS.authId.name }}
            {{- else }}
            secretName: {{ include "cert-manager-webhook-cloudns.fullname" . }}
            {{- end }}
        - name: auth-password
          secret:
            {{- if kindIs "map" .Values.clouDNS.authPassword }}
            secretName: {{ .Values.clouDNS.authPassword.name }}
            {{- else }}
            secretName: {{ include "cert-manager-webhook-cloudns.fullname" . }}
            {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
