apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
    chart: {{ include "cert-manager-webhook-cloudns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if kindIs "string" .Values.clouDNS.authId }}
  authId: {{ .Values.clouDNS.authId | b64enc }}
  {{- end }}
  {{- if kindIs "string" .Values.clouDNS.authPassword }}
  authPassword: {{ .Values.clouDNS.authPassword | b64enc }}
  {{- end }}
