apiVersion: v1
description: A helm chart for cert-manager-webhook-cloudns
name: cert-manager-webhook-cloudns
version: 1.3.0
# renovate: image=ghcr.io/pschichtel/cert-manager-webhook-cloudns
appVersion: "1.2.0"
